import { DutyType } from "./types";

export const mockDate = [
  { id: "date1", label: "Monday" },
  { id: "date2", label: "Tuesday" },
  { id: "date3", label: "Wednesday" },
  { id: "date4", label: "Thursday" },
  { id: "date5", label: "Friday" },
];

export const mockDuties: DutyType[] = [
  {
    id: "morning-up-stairs",
    shiftTime: "morning",
    label: "Morning UpStairs",
    isDuty: true,
  },
  {
    id: "morning-down-stairs",
    shiftTime: "morning",
    label: "Morning DownStairs",
    isDuty: true,
  },
  {
    id: "morning-parking-lot",
    shiftTime: "morning",
    label: "Morning Parking Lot",
    isDuty: true,
  },
  { id: "launch-a", number: 1, label: "Launch A", isDuty: false },
  { id: "launch-b", number: 2, label: "Launch B", isDuty: false },
  { id: "launch-c", number: 3, label: "Launch C", isDuty: false },
  { id: "launch-d", number: 4, label: "Launch D", isDuty: false },
  {
    id: "afternoon-up-stairs",
    shiftTime: "afternoon",
    label: "Afternoon UpStairs",
    isDuty: true,
  },
  {
    id: "afternoon-down-stairs",
    shiftTime: "afternoon",
    label: "Afternoon DownStairs",
    isDuty: true,
  },
  {
    id: "afternoon-parking-lot",
    shiftTime: "afternoon",
    label: "Afternoon Parking Lot",
    isDuty: true,
  },
];

export const mockShifts = {
  "date1-morning-up-stairs": {
    dutyId: "morning-up-stairs",
    dutyLabel: "Morning UpStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-morning-down-stairs": {
    dutyId: "morning-down-stairs",
    dutyLabel: "Morning DownStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-morning-parking-lot": {
    dutyId: "morning-parking-lot",
    dutyLabel: "Morning Parking Lot",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-a": {
    dutyId: "launch-a",
    dutyLabel: "Launch A",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-b": {
    dutyId: "launch-b",
    dutyLabel: "Launch B",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-c": {
    dutyId: "launch-c",
    dutyLabel: "Launch C",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-d": {
    dutyId: "launch-d",
    dutyLabel: "Launch D",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-afternoon-up-stairs": {
    dutyId: "afternoon-up-stairs",
    dutyLabel: "Afternoon UpStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-afternoon-down-stairs": {
    dutyId: "afternoon-down-stairs",
    dutyLabel: "Afternoon DownStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-afternoon-parking-lot": {
    dutyId: "afternoon-parking-lot",
    dutyLabel: "Afternoon Parking Lot",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date2-morning-up-stairs": {
    dutyId: "morning-up-stairs",
    dutyLabel: "Morning UpStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-morning-down-stairs": {
    dutyId: "morning-down-stairs",
    dutyLabel: "Morning DownStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-morning-parking-lot": {
    dutyId: "morning-parking-lot",
    dutyLabel: "Morning Parking Lot",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-a": {
    dutyId: "launch-a",
    dutyLabel: "Launch A",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-b": {
    dutyId: "launch-b",
    dutyLabel: "Launch B",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-c": {
    dutyId: "launch-c",
    dutyLabel: "Launch C",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-d": {
    dutyId: "launch-d",
    dutyLabel: "Launch D",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-afternoon-up-stairs": {
    dutyId: "afternoon-up-stairs",
    dutyLabel: "Afternoon UpStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-afternoon-down-stairs": {
    dutyId: "afternoon-down-stairs",
    dutyLabel: "Afternoon DownStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-afternoon-parking-lot": {
    dutyId: "afternoon-parking-lot",
    dutyLabel: "Afternoon Parking Lot",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date3-morning-up-stairs": {
    dutyId: "morning-up-stairs",
    dutyLabel: "Morning UpStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-morning-down-stairs": {
    dutyId: "morning-down-stairs",
    dutyLabel: "Morning DownStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-morning-parking-lot": {
    dutyId: "morning-parking-lot",
    dutyLabel: "Morning Parking Lot",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-a": {
    dutyId: "launch-a",
    dutyLabel: "Launch A",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-b": {
    dutyId: "launch-b",
    dutyLabel: "Launch B",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-c": {
    dutyId: "launch-c",
    dutyLabel: "Launch C",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-d": {
    dutyId: "launch-d",
    dutyLabel: "Launch D",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-afternoon-up-stairs": {
    dutyId: "afternoon-up-stairs",
    dutyLabel: "Afternoon UpStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-afternoon-down-stairs": {
    dutyId: "afternoon-down-stairs",
    dutyLabel: "Afternoon DownStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-afternoon-parking-lot": {
    dutyId: "afternoon-parking-lot",
    dutyLabel: "Afternoon Parking Lot",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date4-morning-up-stairs": {
    dutyId: "morning-up-stairs",
    dutyLabel: "Morning UpStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-morning-down-stairs": {
    dutyId: "morning-down-stairs",
    dutyLabel: "Morning DownStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-morning-parking-lot": {
    dutyId: "morning-parking-lot",
    dutyLabel: "Morning Parking Lot",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-a": {
    dutyId: "launch-a",
    dutyLabel: "Launch A",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-b": {
    dutyId: "launch-b",
    dutyLabel: "Launch B",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-c": {
    dutyId: "launch-c",
    dutyLabel: "Launch C",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-d": {
    dutyId: "launch-d",
    dutyLabel: "Launch D",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-afternoon-up-stairs": {
    dutyId: "afternoon-up-stairs",
    dutyLabel: "Afternoon UpStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-afternoon-down-stairs": {
    dutyId: "afternoon-down-stairs",
    dutyLabel: "Afternoon DownStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-afternoon-parking-lot": {
    dutyId: "afternoon-parking-lot",
    dutyLabel: "Afternoon Parking Lot",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date5-morning-up-stairs": {
    dutyId: "morning-up-stairs",
    dutyLabel: "Morning UpStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-morning-down-stairs": {
    dutyId: "morning-down-stairs",
    dutyLabel: "Morning DownStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-morning-parking-lot": {
    dutyId: "morning-parking-lot",
    dutyLabel: "Morning Parking Lot",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-a": {
    dutyId: "launch-a",
    dutyLabel: "Launch A",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-b": {
    dutyId: "launch-b",
    dutyLabel: "Launch B",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-c": {
    dutyId: "launch-c",
    dutyLabel: "Launch C",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-d": {
    dutyId: "launch-d",
    dutyLabel: "Launch D",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-afternoon-up-stairs": {
    dutyId: "afternoon-up-stairs",
    dutyLabel: "Afternoon UpStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-afternoon-down-stairs": {
    dutyId: "afternoon-down-stairs",
    dutyLabel: "Afternoon DownStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-afternoon-parking-lot": {
    dutyId: "afternoon-parking-lot",
    dutyLabel: "Afternoon Parking Lot",
    dateId: "date5",
    dateLabel: "Friday",
  },
};
export const mockStaffs = {
  staff1: { name: "X1", id: "staff1", shifts: {}, totalShifts: 0 },
  staff2: { name: "X2", id: "staff2", shifts: {}, totalShifts: 0 },
  staff3: { name: "X3", id: "staff3", shifts: {}, totalShifts: 0 },
  staff4: { name: "X4", id: "staff4", shifts: {}, totalShifts: 0 },
  staff5: { name: "X5", id: "staff5", shifts: {}, totalShifts: 0 },
  staff6: { name: "X6", id: "staff6", shifts: {}, totalShifts: 0 },
  staff7: { name: "X7", id: "staff7", shifts: {}, totalShifts: 0 },
};
