export const mockDate = [
  { id: "date1", label: "Monday" },
  { id: "date2", label: "Tuesday" },
  { id: "date3", label: "Wednesday" },
  { id: "date4", label: "Thursday" },
  { id: "date5", label: "Friday" },
];

export const mockActivities = [
  { id: "morning-up-stairs", label: "Morning UpStairs" },
  { id: "morning-down-stairs", label: "Morning DownStairs" },
  { id: "morning-parking-lot", label: "Morning Parking Lot" },
  { id: "launch-a", label: "Launch A" },
  { id: "launch-b", label: "Launch B" },
  { id: "launch-c", label: "Launch C" },
  { id: "launch-d", label: "Launch D" },
  { id: "afternoon-up-stairs", label: "Afternoon UpStairs" },
  { id: "afternoon-down-stairs", label: "Afternoon DownStairs" },
  { id: "afternoon-parking-lot", label: "Afternoon Parking Lot" },
];

export const mockShifts = {
  "date1-morning-up-stairs": {
    activityId: "morning-up-stairs",
    activityLabel: "Morning UpStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-morning-down-stairs": {
    activityId: "morning-down-stairs",
    activityLabel: "Morning DownStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-morning-parking-lot": {
    activityId: "morning-parking-lot",
    activityLabel: "Morning Parking Lot",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-a": {
    activityId: "launch-a",
    activityLabel: "Launch A",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-b": {
    activityId: "launch-b",
    activityLabel: "Launch B",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-c": {
    activityId: "launch-c",
    activityLabel: "Launch C",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-launch-d": {
    activityId: "launch-d",
    activityLabel: "Launch D",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-afternoon-up-stairs": {
    activityId: "afternoon-up-stairs",
    activityLabel: "Afternoon UpStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-afternoon-down-stairs": {
    activityId: "afternoon-down-stairs",
    activityLabel: "Afternoon DownStairs",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date1-afternoon-parking-lot": {
    activityId: "afternoon-parking-lot",
    activityLabel: "Afternoon Parking Lot",
    dateId: "date1",
    dateLabel: "Monday",
  },
  "date2-morning-up-stairs": {
    activityId: "morning-up-stairs",
    activityLabel: "Morning UpStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-morning-down-stairs": {
    activityId: "morning-down-stairs",
    activityLabel: "Morning DownStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-morning-parking-lot": {
    activityId: "morning-parking-lot",
    activityLabel: "Morning Parking Lot",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-a": {
    activityId: "launch-a",
    activityLabel: "Launch A",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-b": {
    activityId: "launch-b",
    activityLabel: "Launch B",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-c": {
    activityId: "launch-c",
    activityLabel: "Launch C",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-launch-d": {
    activityId: "launch-d",
    activityLabel: "Launch D",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-afternoon-up-stairs": {
    activityId: "afternoon-up-stairs",
    activityLabel: "Afternoon UpStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-afternoon-down-stairs": {
    activityId: "afternoon-down-stairs",
    activityLabel: "Afternoon DownStairs",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date2-afternoon-parking-lot": {
    activityId: "afternoon-parking-lot",
    activityLabel: "Afternoon Parking Lot",
    dateId: "date2",
    dateLabel: "Tuesday",
  },
  "date3-morning-up-stairs": {
    activityId: "morning-up-stairs",
    activityLabel: "Morning UpStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-morning-down-stairs": {
    activityId: "morning-down-stairs",
    activityLabel: "Morning DownStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-morning-parking-lot": {
    activityId: "morning-parking-lot",
    activityLabel: "Morning Parking Lot",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-a": {
    activityId: "launch-a",
    activityLabel: "Launch A",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-b": {
    activityId: "launch-b",
    activityLabel: "Launch B",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-c": {
    activityId: "launch-c",
    activityLabel: "Launch C",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-launch-d": {
    activityId: "launch-d",
    activityLabel: "Launch D",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-afternoon-up-stairs": {
    activityId: "afternoon-up-stairs",
    activityLabel: "Afternoon UpStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-afternoon-down-stairs": {
    activityId: "afternoon-down-stairs",
    activityLabel: "Afternoon DownStairs",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date3-afternoon-parking-lot": {
    activityId: "afternoon-parking-lot",
    activityLabel: "Afternoon Parking Lot",
    dateId: "date3",
    dateLabel: "Wednesday",
  },
  "date4-morning-up-stairs": {
    activityId: "morning-up-stairs",
    activityLabel: "Morning UpStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-morning-down-stairs": {
    activityId: "morning-down-stairs",
    activityLabel: "Morning DownStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-morning-parking-lot": {
    activityId: "morning-parking-lot",
    activityLabel: "Morning Parking Lot",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-a": {
    activityId: "launch-a",
    activityLabel: "Launch A",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-b": {
    activityId: "launch-b",
    activityLabel: "Launch B",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-c": {
    activityId: "launch-c",
    activityLabel: "Launch C",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-launch-d": {
    activityId: "launch-d",
    activityLabel: "Launch D",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-afternoon-up-stairs": {
    activityId: "afternoon-up-stairs",
    activityLabel: "Afternoon UpStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-afternoon-down-stairs": {
    activityId: "afternoon-down-stairs",
    activityLabel: "Afternoon DownStairs",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date4-afternoon-parking-lot": {
    activityId: "afternoon-parking-lot",
    activityLabel: "Afternoon Parking Lot",
    dateId: "date4",
    dateLabel: "Thursday",
  },
  "date5-morning-up-stairs": {
    activityId: "morning-up-stairs",
    activityLabel: "Morning UpStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-morning-down-stairs": {
    activityId: "morning-down-stairs",
    activityLabel: "Morning DownStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-morning-parking-lot": {
    activityId: "morning-parking-lot",
    activityLabel: "Morning Parking Lot",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-a": {
    activityId: "launch-a",
    activityLabel: "Launch A",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-b": {
    activityId: "launch-b",
    activityLabel: "Launch B",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-c": {
    activityId: "launch-c",
    activityLabel: "Launch C",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-launch-d": {
    activityId: "launch-d",
    activityLabel: "Launch D",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-afternoon-up-stairs": {
    activityId: "afternoon-up-stairs",
    activityLabel: "Afternoon UpStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-afternoon-down-stairs": {
    activityId: "afternoon-down-stairs",
    activityLabel: "Afternoon DownStairs",
    dateId: "date5",
    dateLabel: "Friday",
  },
  "date5-afternoon-parking-lot": {
    activityId: "afternoon-parking-lot",
    activityLabel: "Afternoon Parking Lot",
    dateId: "date5",
    dateLabel: "Friday",
  },
};
export const mockStaffs = {
  staff1: { name: "X1", id: "staff1", shifts: {} },
  staff2: { name: "X2", id: "staff2", shifts: {} },
  staff3: { name: "X3", id: "staff3", shifts: {} },
  staff4: { name: "X4", id: "staff4", shifts: {} },
  staff5: { name: "X5", id: "staff5", shifts: {} },
  staff6: { name: "X6", id: "staff6", shifts: {} },
  staff7: { name: "X7", id: "staff7", shifts: {} },
};
